[project]
name = "ad-bs-converter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[authors]
name = "Aayush Dip Giri"
email = "your-email@example.com"

[license]
text = "MIT"